<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('department_menus', function (Blueprint $table) {
            // Keys
            $table->bigIncrements('id');
            $table->char('uuid', 36)->unique();                  // app-level stable id

            // Ownership / hierarchy
            $table->unsignedBigInteger('department_id');         // FK -> departments.id
            $table->unsignedBigInteger('parent_id')->nullable(); // self FK for parent/child

            // Core
            $table->string('title', 150);
            $table->text('description')->nullable();

            // Routing / identity
            $table->string('slug', 160);                         // page slug to load
            $table->string('code', 24)->nullable()->unique();    // optional, autogenerated unique

            // Behaviour
            $table->boolean('is_default')->default(false);       // default child to auto-load
            $table->unsignedInteger('position')->default(0);     // for ordering (drag & drop)
            $table->boolean('active')->default(true);            // toggle visibility (useful in UI)

            // Timestamps (consistent with your style)
            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();
            $table->softDeletes(); // deleted_at

            // Audit
            $table->unsignedBigInteger('created_by')->nullable();
            $table->unsignedBigInteger('updated_by')->nullable();
            $table->string('created_at_ip', 45)->nullable();
            $table->string('updated_at_ip', 45)->nullable();

            // Indexes & constraints
            $table->unique(['department_id', 'slug']);           // one slug per department
            $table->index(['department_id', 'parent_id']);       // fast fetch by parent
            $table->index(['parent_id', 'position']);            // stable ordering within siblings
            $table->index('is_default');                          // quick default lookup
            $table->index('active');

            $table->foreign('department_id')
                  ->references('id')->on('departments')
                  ->onDelete('cascade');                         // remove menus if department is removed

            $table->foreign('parent_id')
                  ->references('id')->on('department_menus')
                  ->onDelete('cascade');                         // delete subtree when parent is removed
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('department_menus');
    }
};
